//
//  Platform.swift
//  URLValidator
//
//  Created by David Sherlock on 09/08/2025.
//

import Foundation

/// Supported platforms with intelligent detection
public enum Platform: String, CaseIterable, Sendable {
    
    // MARK: Video Platforms
    case youtube = "YouTube"
    case youtubeMusic = "YouTube Music"
    case youtubeShorts = "YouTube Shorts"
    case youtubeStudio = "YouTube Studio"
    case vimeo = "Vimeo"
    case dailymotion = "Dailymotion"
    case twitch = "Twitch"
    case kick = "Kick"
    case rumble = "Rumble"
    case bitchute = "BitChute"
    case odysee = "Odysee"
    case peertube = "PeerTube"
    case dtube = "DTube"
    case veoh = "Veoh"
    case metacafe = "Metacafe"
    case brighteon = "Brighteon"
    case banned = "Banned.video"
    case rokfin = "Rokfin"
    case floatplane = "Floatplane"
    case nebula = "Nebula"
    case lbry = "LBRY"
    
    // MARK: Short-form Video
    case tiktok = "TikTok"
    case instagram = "Instagram"
    case instagramReels = "Instagram Reels"
    case snapchat = "Snapchat"
    case douyin = "Douyin"
    case kuaishou = "Kuaishou"
    case likee = "Likee"
    case triller = "Triller"
    case byte = "Byte"
    case clash = "Clash"
    
    // MARK: Audio/Music Platforms
    case spotify = "Spotify"
    case appleMusic = "Apple Music"
    case applePodcasts = "Apple Podcasts"
    case soundcloud = "SoundCloud"
    case bandcamp = "Bandcamp"
    case deezer = "Deezer"
    case tidal = "Tidal"
    case amazonMusic = "Amazon Music"
    case pandora = "Pandora"
    case audiomack = "Audiomack"
    case qobuz = "Qobuz"
    case mixcloud = "Mixcloud"
    case beatport = "Beatport"
    case napster = "Napster"
    case iheartradio = "iHeartRadio"
    case tunein = "TuneIn"
    case anghami = "Anghami"
    case gaana = "Gaana"
    case jiosaavn = "JioSaavn"
    case lastfm = "Last.fm"
    case genius = "Genius"
    
    // MARK: Podcast Platforms
    case anchor = "Anchor"
    case pocketCasts = "PocketCasts"
    case overcast = "Overcast"
    case castbox = "Castbox"
    case googlePodcasts = "Google Podcasts"
    case stitcher = "Stitcher"
    case podbean = "Podbean"
    case buzzsprout = "Buzzsprout"
    case podcastsSpotify = "Spotify Podcasters"
    case podcastAddict = "Podcast Addict"
    case castro = "Castro"
    
    // MARK: Social Media
    case facebook = "Facebook"
    case twitter = "Twitter/X"
    case linkedin = "LinkedIn"
    case reddit = "Reddit"
    case pinterest = "Pinterest"
    case tumblr = "Tumblr"
    case mastodon = "Mastodon"
    case threads = "Threads"
    case bluesky = "Bluesky"
    case truthSocial = "Truth Social"
    case gab = "Gab"
    case parler = "Parler"
    case mewe = "MeWe"
    case gettr = "Gettr"
    case minds = "Minds"
    case locals = "Locals"
    case vero = "Vero"
    case ello = "Ello"
    case diaspora = "Diaspora"
    
    // MARK: Asian Social Platforms
    case weibo = "Weibo"
    case wechat = "WeChat"
    case qq = "QQ"
    case xiaohongshu = "Xiaohongshu"
    case bilibili = "Bilibili"
    case youku = "Youku"
    case niconico = "Niconico"
    case kakaotalk = "KakaoTalk"
    case line = "Line"
    case viber = "Viber"
    case zalo = "Zalo"
    case vk = "VK"
    
    // MARK: Messaging/Communication
    case whatsapp = "WhatsApp"
    case telegram = "Telegram"
    case discord = "Discord"
    case slack = "Slack"
    case signal = "Signal"
    case messenger = "Messenger"
    case element = "Element"
    case matrix = "Matrix"
    case threema = "Threema"
    case wire = "Wire"
    case session = "Session"
    case keybase = "Keybase"
    
    // MARK: Live Streaming
    case twitchLive = "Twitch Live"
    case facebookGaming = "Facebook Gaming"
    case youtubeGaming = "YouTube Gaming"
    case dlive = "DLive"
    case caffeine = "Caffeine"
    case trovo = "Trovo"
    case picarto = "Picarto"
    case younow = "YouNow"
    case bigoLive = "Bigo Live"
    case streamyard = "StreamYard"
    case streamlabs = "Streamlabs"
    case restream = "Restream"
    case obsLive = "OBS.Live"
    
    // MARK: Professional/Developer
    case github = "GitHub"
    case gitlab = "GitLab"
    case bitbucket = "Bitbucket"
    case stackoverflow = "Stack Overflow"
    case codepen = "CodePen"
    case codesandbox = "CodeSandbox"
    case replit = "Replit"
    case figma = "Figma"
    case dribbble = "Dribbble"
    case behance = "Behance"
    case angellist = "AngelList"
    case producthunt = "Product Hunt"
    case polywork = "Polywork"
    case wellfound = "Wellfound"
    case glitch = "Glitch"
    case kaggle = "Kaggle"
    case vercel = "Vercel"
    case netlify = "Netlify"
    
    // MARK: E-commerce
    case amazon = "Amazon"
    case ebay = "eBay"
    case etsy = "Etsy"
    case shopify = "Shopify"
    case alibaba = "Alibaba"
    case aliexpress = "AliExpress"
    case mercari = "Mercari"
    case poshmark = "Poshmark"
    case depop = "Depop"
    case walmart = "Walmart"
    case target = "Target"
    case bestbuy = "Best Buy"
    case wish = "Wish"
    case shein = "SHEIN"
    case wayfair = "Wayfair"
    
    // MARK: Gaming Platforms
    case steam = "Steam"
    case epicGames = "Epic Games"
    case battlenet = "Battle.net"
    case origin = "Origin"
    case uplay = "Uplay"
    case gog = "GOG"
    case itchIo = "itch.io"
    case roblox = "Roblox"
    case minecraft = "Minecraft"
    case fortnite = "Fortnite"
    case leagueOfLegends = "League of Legends"
    case valorant = "Valorant"
    case xbox = "Xbox"
    case playstation = "PlayStation"
    case nintendo = "Nintendo"
    
    // MARK: Financial/Crypto

    // Payment Processors
    case paypal = "PayPal"
    case venmo = "Venmo"
    case cashapp = "Cash App"
    case zelle = "Zelle"
    case stripe = "Stripe"
    case square = "Square"
    case alipay = "Alipay"
    case paytm = "Paytm"

    // Buy Now, Pay Later
    case klarna = "Klarna"
    case afterpay = "Afterpay"
    case affirm = "Affirm"

    // Digital Banking
    case chime = "Chime"
    case revolut = "Revolut"
    case wise = "Wise"

    // Trading/Investment
    case robinhood = "Robinhood"
    case etoro = "eToro"
    case webull = "Webull"

    // Crypto
    case coinbase = "Coinbase"
    case binance = "Binance"
    case kraken = "Kraken"
    case metamask = "MetaMask"
    case cryptoDotCom = "Crypto.com"
    
    // MARK: Dating Platforms
    case tinder = "Tinder"
    case bumble = "Bumble"
    case hinge = "Hinge"
    case match = "Match"
    case okcupid = "OkCupid"
    case plentyoffish = "PlentyOfFish"
    case eharmony = "eHarmony"
    case coffeeMeetsBagel = "Coffee Meets Bagel"
    case happn = "Happn"
    case badoo = "Badoo"
    case grindr = "Grindr"
    case her = "Her"
    case feeld = "Feeld"
    
    // MARK: Cloud Storage
    case dropbox = "Dropbox"
    case googleDrive = "Google Drive"
    case onedrive = "OneDrive"
    case box = "Box"
    case icloud = "iCloud"
    case mega = "Mega"
    case pcloud = "pCloud"
    case sync = "Sync"
    case mediafire = "MediaFire"
    case wetransfer = "WeTransfer"
    
    // MARK: News/Publishing
    case medium = "Medium"
    case substack = "Substack"
    case wordpress = "WordPress"
    case blogger = "Blogger"
    case ghost = "Ghost"
    case mirror = "Mirror"
    case revue = "Revue"
    case convertkit = "ConvertKit"
    case beehiiv = "Beehiiv"
    case hashnode = "Hashnode"
    case devto = "Dev.to"
    
    // MARK: E-Learning
    case udemy = "Udemy"
    case coursera = "Coursera"
    case edx = "edX"
    case skillshare = "Skillshare"
    case teachable = "Teachable"
    case thinkific = "Thinkific"
    case kajabi = "Kajabi"
    case linkedinLearning = "LinkedIn Learning"
    case khanAcademy = "Khan Academy"
    case udacity = "Udacity"
    case pluralsight = "Pluralsight"
    case masterclass = "MasterClass"
    case brilliantorg = "Brilliant.org"
    
    // MARK: Web3/Crypto/NFT
    case opensea = "OpenSea"
    case rarible = "Rarible"
    case foundation = "Foundation"
    case superrare = "SuperRare"
    case zora = "Zora"
    case lensProtocol = "Lens Protocol"
    case farcaster = "Farcaster"
    case decentraland = "Decentraland"
    case cryptoVoxels = "CryptoVoxels"
    case sandbox = "The Sandbox"
    case axieInfinity = "Axie Infinity"
    
    // MARK: Video Conferencing
    case zoom = "Zoom"
    case teams = "Microsoft Teams"
    case googleMeet = "Google Meet"
    case skype = "Skype"
    case webex = "Webex"
    case whereby = "Whereby"
    case jitsi = "Jitsi"
    case gotomeeting = "GoToMeeting"
    case bluejeans = "BlueJeans"
    
    // MARK: Maps/Navigation
    case googleMaps = "Google Maps"
    case appleMaps = "Apple Maps"
    case waze = "Waze"
    case openstreetmap = "OpenStreetMap"
    case mapbox = "Mapbox"
    case hereWeGo = "HERE WeGo"
    case citymapper = "Citymapper"
    
    // MARK: Food Delivery
    case ubereats = "Uber Eats"
    case doordash = "DoorDash"
    case grubhub = "Grubhub"
    case postmates = "Postmates"
    case instacart = "Instacart"
    case deliveroo = "Deliveroo"
    case justeat = "Just Eat"
    case seamless = "Seamless"
    
    // MARK: Travel/Booking
    case airbnb = "Airbnb"
    case booking = "Booking.com"
    case expedia = "Expedia"
    case tripadvisor = "TripAdvisor"
    case kayak = "Kayak"
    case hotels = "Hotels.com"
    case vrbo = "VRBO"
    case agoda = "Agoda"
    
    // MARK: Productivity
    case notion = "Notion"
    case airtable = "Airtable"
    case trello = "Trello"
    case miro = "Miro"
    case canva = "Canva"
    case wikipedia = "Wikipedia"
    case linktree = "Linktree"
    case carrd = "Carrd"
    case asana = "Asana"
    case monday = "Monday.com"
    case clickup = "ClickUp"
    case jira = "Jira"
    
    // MARK: Subscription/Creator Platforms
    case onlyfans = "OnlyFans"
    case patreon = "Patreon"
    case fansly = "Fansly"
    case kofi = "Ko-fi"
    case buymeacoffee = "Buy Me a Coffee"
    case gumroad = "Gumroad"
    case subscribestar = "SubscribeStar"
    
    // Unknown
    case unknown = "Unknown"
    
}
